#! /bin/bash

# This file will take a clip from a movie and perform certain operations on it. 


# VIDEO 1 Operations
	# Trim: 8:00 to 11:00
	# Sync/trim the audio for that section of film
	#
	# Display Frequency spectrum underneath
	# Display Power Spectrum Underneath
	# Display Something to the side of the video and the bottom will be colored green.
	# Histogram

# VIDEO2 Operations
	# Trim: 20:11 to 21:46
	# OVERLAY to mirror Top half onto bottom half
	# Overlay to Put bottom half on top half and top half on bottom half
	# Blur the video
	# ROTATE video in sinusoidal manner
	# 
	
# VIDEO3 Operations
	# Trim: 22:50 to 23:57
	# Exponential Saturation Fade-Out with HUE
	# Full Color
	# Red Channel Only: COLORCHANNELMIXER
	# Green Channel Only
	# Blue Channel Only
	# Full Color
	# CROP but PAD with purple
	# Lower Framerate to 10 fps:  FPS
	# Chorus Delay on Audio
	# Play with geq, hflip, 
# https://trac.ffmpeg.org/wiki/FancyFilteringExamples
# https://trac.ffmpeg.org/wiki/FilteringGuide

# FINAL OPERATIONS
	# Add subtitles to the entire video detailing which settings I have used at each effecrt change. SUBTITLES
	# TODO: Make a .srt file.







## DECLARE VARS
TEST="/Users/xavier/Downloads/mov/A.Beautiful.Mind.2001.1080p/A.Beautiful.Mind.2001.1080p.BluRay.x264.GSFTX.mp4"
T1=480  # 00:08:00
T2=660  # 00:11:00
T3=1211 # 00:20:11
T4=1306 # 00:21:46
T5=1370 # 00:22:50
T6=1437 # 00:23:27

ffmpeg -i $TEST \
	-async 1 \
	-filter_complex \
		"[0:v]trim=$T1:$T2, setpts=PTS-STARTPTS[v0]; \
		 [0:a]atrim=$T1:$T2, asetpts=PTS-STARTPTS, \
			showfreqs=size="1920x520":mode=line, \
			scale=w=iw:h=0.5*ih[v0-1]; \
		 [0:a]atrim=$T1:$T2, asetpts=PTS-STARTPTS[a0]; \
		 [0:v]trim=$T3:$T4, setpts=PTS-STARTPTS[v1]; \
	 	 [v1]hue="H=2*PI*t:s=3"[v1-hue]; \
		 [0:a]atrim=$T3:$T4, asetpts=PTS-STARTPTS[a1]; \
		 [0:v]trim=$T5:$T6, setpts=PTS-STARTPTS[v2]; \
		 [0:a]atrim=$T5:$T6, asetpts=PTS-STARTPTS[a2]; \
		 [v0][v0-1]overlay=x=main_w-overlay_w-10:y=main_h-overlay_h-10[v0-over]; \
		 [v0-over][a0][v1-hue][a1][v2][a2]concat=n=3:v=1:a=1[out]" \
	-b:a 192k \
	-strict -2 \
	-y \
	-map "[out]" \
	output.mkv






